/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/properties/": {
    /** List Properties */
    get: operations["list_properties_properties__get"];
    /** Create Property */
    post: operations["create_property_properties__post"];
  };
  "/properties/{property_id}": {
    /** Get Property */
    get: operations["get_property_properties__property_id__get"];
    /** Update Property */
    put: operations["update_property_properties__property_id__put"];
    /** Delete Property */
    delete: operations["delete_property_properties__property_id__delete"];
    /** Patch Property */
    patch: operations["patch_property_properties__property_id__patch"];
  };
  "/tenants/": {
    /** List Tenants */
    get: operations["list_tenants_tenants__get"];
    /** Create Tenant */
    post: operations["create_tenant_tenants__post"];
  };
  "/tenants/{tenant_id}": {
    /** Get Tenant */
    get: operations["get_tenant_tenants__tenant_id__get"];
    /** Update Tenant */
    put: operations["update_tenant_tenants__tenant_id__put"];
    /** Delete Tenant */
    delete: operations["delete_tenant_tenants__tenant_id__delete"];
    /** Patch Tenant */
    patch: operations["patch_tenant_tenants__tenant_id__patch"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** PropertyCreate */
    PropertyCreate: {
      /** Address */
      address: string;
      /** Bedrooms */
      bedrooms?: number | null;
      /** Bathrooms */
      bathrooms?: number | null;
      /** Area */
      area?: number | null;
      /** Rent Amount */
      rent_amount?: number | string | null;
      /** Status */
      status?: string | null;
    };
    /** PropertyPatch */
    PropertyPatch: {
      /** Address */
      address?: string | null;
      /** Bedrooms */
      bedrooms?: number | null;
      /** Bathrooms */
      bathrooms?: number | null;
      /** Area */
      area?: number | null;
      /** Rent Amount */
      rent_amount?: number | string | null;
      /** Status */
      status?: string | null;
    };
    /** PropertyRead */
    PropertyRead: {
      /** Address */
      address: string;
      /** Bedrooms */
      bedrooms?: number | null;
      /** Bathrooms */
      bathrooms?: number | null;
      /** Area */
      area?: number | null;
      /** Rent Amount */
      rent_amount?: string | null;
      /** Status */
      status?: string | null;
      /** Id */
      id: number;
      /** Created At */
      created_at: string | null;
    };
    /** PropertyUpdate */
    PropertyUpdate: {
      /** Address */
      address: string;
      /** Bedrooms */
      bedrooms?: number | null;
      /** Bathrooms */
      bathrooms?: number | null;
      /** Area */
      area?: number | null;
      /** Rent Amount */
      rent_amount?: number | string | null;
      /** Status */
      status?: string | null;
    };
    /** TenantCreate */
    TenantCreate: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Status */
      status?: string | null;
    };
    /** TenantRead */
    TenantRead: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Status */
      status?: string | null;
      /** Id */
      id: number;
      /** Created At */
      created_at: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List Properties */
  list_properties_properties__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Property */
  create_property_properties__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Property */
  get_property_properties__property_id__get: {
    parameters: {
      path: {
        property_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Property */
  update_property_properties__property_id__put: {
    parameters: {
      path: {
        property_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertyUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Property */
  delete_property_properties__property_id__delete: {
    parameters: {
      path: {
        property_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Property */
  patch_property_properties__property_id__patch: {
    parameters: {
      path: {
        property_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertyPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Tenants */
  list_tenants_tenants__get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Tenant */
  create_tenant_tenants__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Tenant */
  get_tenant_tenants__tenant_id__get: {
    parameters: {
      path: {
        tenant_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Tenant */
  update_tenant_tenants__tenant_id__put: {
    parameters: {
      path: {
        tenant_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Tenant */
  delete_tenant_tenants__tenant_id__delete: {
    parameters: {
      path: {
        tenant_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Tenant */
  patch_tenant_tenants__tenant_id__patch: {
    parameters: {
      path: {
        tenant_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
