"""Create initial tables

Revision ID: 5435ab0f73ad
Revises: 1a1a1a1a1a1a
Create Date: 2025-11-01 18:25:38.432044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5435ab0f73ad'
down_revision: Union[str, None] = '1a1a1a1a1a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index(op.f('ix_pm_properties_id'), 'properties', ['id'], unique=False, schema='pm')
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='pm'
    )
    op.create_index(op.f('ix_pm_tenants_id'), 'tenants', ['id'], unique=False, schema='pm')
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['pm.properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['pm.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index(op.f('ix_pm_files_id'), 'files', ['id'], unique=False, schema='pm')
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['pm.properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['pm.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index(op.f('ix_pm_leases_id'), 'leases', ['id'], unique=False, schema='pm')
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['pm.properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['pm.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index(op.f('ix_pm_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False, schema='pm')
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['pm.properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['pm.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pm'
    )
    op.create_index(op.f('ix_pm_transactions_id'), 'transactions', ['id'], unique=False, schema='pm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pm_transactions_id'), table_name='transactions', schema='pm')
    op.drop_table('transactions', schema='pm')
    op.drop_index(op.f('ix_pm_maintenance_requests_id'), table_name='maintenance_requests', schema='pm')
    op.drop_table('maintenance_requests', schema='pm')
    op.drop_index(op.f('ix_pm_leases_id'), table_name='leases', schema='pm')
    op.drop_table('leases', schema='pm')
    op.drop_index(op.f('ix_pm_files_id'), table_name='files', schema='pm')
    op.drop_table('files', schema='pm')
    op.drop_index(op.f('ix_pm_tenants_id'), table_name='tenants', schema='pm')
    op.drop_table('tenants', schema='pm')
    op.drop_index(op.f('ix_pm_properties_id'), table_name='properties', schema='pm')
    op.drop_table('properties', schema='pm')
    # ### end Alembic commands ###
